spring.application.name=order-service


# Config Server Baglantisi
# Docker ortaminda CONFIG_URI degiskeni gecilirse onu alir, yoksa localhost kullanir
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# Profil fallback (docker/local otomatik secilebilir)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Eureka Client (Docker veya local uzerinden override edilebilir)
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Management / Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator

# Diger
spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false



springdoc.api-docs.path=/api/orders/v3/api-docs
server.forward-headers-strategy=framework

# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50

resilience4j.circuitbreaker.instances.paymentService.baseConfig=default
resilience4j.circuitbreaker.instances.stockService.baseConfig=default

# Resilience4j Retry Config
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=2s
resilience4j.retry.instances.paymentService.baseConfig=default
resilience4j.retry.instances.stockService.baseConfig=default

# Feign Circuit Breaker Enable
spring.cloud.openfeign.circuitbreaker.enabled=true
